name: Activity Box

on:
  schedule:
    - cron: '* */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: 4bigchoi23/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: 4bigchoi23
          GIST_ID: 8e85cf422c33e290a8a5aa486918e554
